title:             Hello , i m lee yong hee
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "/"
url:               "https://leeyh2006.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Author Settings
author-img: LeeYongHee.jpg # add your photo
about-author: 슈퍼 개발자 ^^ # add description
social-twitter: # add your Twitter handle
social-facebook: "facebook.com/yonghee.lee.9843" # add your Facebook handle
social-github: "https://github.com/leeyh2006" # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: "leeyh2006@nate.com"# add your Email address

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
